# Generated by Django 3.1.7 on 2021-04-21 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wam_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wam_interface.contactsgroup'),
        ),
    ]
