# Generated by Django 3.1.7 on 2021-04-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wam_interface', '0002_contact_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('message_1', models.CharField(max_length=200, null=True)),
                ('message_2', models.CharField(max_length=200, null=True)),
                ('message_3', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
