# Generated by Django 3.1.7 on 2021-04-28 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wam_interface', '0004_botconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wam_interface.contactsgroup'),
        ),
    ]
